# Generated by Django 2.2.5 on 2019-09-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busid', models.CharField(max_length=20)),
                ('siteinbus', models.IntegerField()),
                ('stationname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.Station')),
            ],
        ),
    ]
