# Generated by Django 2.2.5 on 2019-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('busid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
